#!/bin/sh
set -eux

WORKSPACE_PATH=~/Workspace
HOSTNAME=`cat $WORKSPACE_PATH/dotbash/.hostname`

cd $WORKSPACE_PATH/dotbash/configs/$HOSTNAME

if hash brew 2>/dev/null && [[ -f Brewfile ]]
then
  brew bundle dump --force
fi

if hash pip 2>/dev/null && [[ -f requirements.txt ]]
then
  pip freeze > requirements.txt
fi
