#!/bin/sh
set -euxo pipefail

WORKSPACE_PATH=~/Workspace
HOSTNAME=`cat $WORKSPACE_PATH/dotbash/.hostname`

cd $WORKSPACE_PATH/dotbash/configs/$HOSTNAME

if hash brew 2>/dev/null
then
  brew bundle dump --force
fi

if hash pip 2>/dev/null
then
  pip freeze > requirements.txt
fi
