tap "bramstein/webfonttools"
tap "homebrew/brewdler"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "stripe/stripe-cli"
brew "gdbm"
brew "gettext"
brew "ossp-uuid"
brew "sqlite"
brew "xz"
brew "autojump", link: false
brew "automake"
brew "bash", link: false
brew "bash-completion"
brew "bazel"
brew "cfssl"
brew "cscope"
brew "openldap"
brew "curl"
brew "ddrescue"
brew "dialog"
brew "dos2unix"
brew "fasd"
brew "libpng"
brew "freetype"
brew "libtiff"
brew "git-crypt"
brew "libffi"
brew "pcre"
brew "glib", link: false
brew "gnu-sed"
brew "gnu-tar"
brew "libevent"
brew "gnupg", link: false
brew "gradle"
brew "httrack"
brew "openjpeg"
brew "webp"
brew "imagemagick", link: false
brew "iperf"
brew "jq"
brew "lame"
brew "ldns"
brew "libexif", link: false
brew "mas"
brew "minikube"
brew "mmv"
brew "mr"
brew "mysql-client"
brew "nmap"
brew "node"
brew "nvm"
brew "openssh", link: false
brew "optipng"
brew "packer"
brew "parallel"
brew "pth"
brew "pyenv"
brew "python@3.8"
brew "rbenv"
brew "ssed", link: false
brew "sysbench", link: false
brew "terraform"
brew "terraform@0.13"
brew "the_silver_searcher"
brew "tmux", link: false
brew "tree"
brew "ttf2eot"
brew "watch", link: false
brew "wget", link: false
brew "bramstein/webfonttools/sfnt2woff-zopfli"
brew "bramstein/webfonttools/woff2"
brew "stripe/stripe-cli/stripe"
cask "1password"
cask "adobe-creative-cloud"
cask "android-file-transfer"
cask "docker"
cask "evernote"
cask "font-hack"
cask "google-backup-and-sync"
cask "google-chrome"
cask "intellij-idea"
cask "iterm2"
cask "keka"
cask "osxfuse"
cask "skype"
cask "slate"
cask "spotify"
cask "sublime-text"
cask "transmission"
cask "virtualbox"
cask "vlc"
mas "Amphetamine", id: 937984704
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "NordVPN IKE", id: 1116599239
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
